web: daphne -b 0.0.0.0 -p $PORT -t 200 realtime_platform.asgi:application
worker: celery -A realtime_platform worker --loglevel=info --concurrency=2
beat: celery -A realtime_platform beat --loglevel=info
